services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP 프로토콜 기본 포트
      - "15672:15672"  # 관리 콘솔 웹 UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  # 데이터 영속화

volumes:
  rabbitmq-data:
